version: "3.4"

volumes:
  astro_node_modules:

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - programming-api
      - programming-ui
    ports:
      - 7800:7800
  
  rabbitmq:
      build: rabbitmq/.
      ports:
        - 5672:5672
        - 15672:15672
      healthcheck: 
        test: rabbitmq-diagnostics check_port_connectivity
        interval: 10s
        timeout: 5s
        retries: 5

  grader-api:
    build: grader-api
    image: grader-api
    restart: "on-failure"
    volumes:
      - ./grader-api/:/app
      - ./app-cache/:/app-cache
      - "/var/run/docker.sock:/var/run/docker.sock"
    expose:
      - 7000
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true

  programming-api:
    build: 
      context: programming-api
      dockerfile: Dockerfile.prod
    image: programming-api-prod
    restart: "on-failure"
    volumes:
      - ./programming-api/:/app
      - ./app-cache/:/app-cache
    expose:
      - 7777
    depends_on:
      - database
      - flyway
    env_file:
      - project.env
    deploy:
      replicas: 2

  programming-ui:
    build: 
      context: programming-ui
      dockerfile: Dockerfile.prod
    image: programming-ui-prod
    restart: "on-failure"
    ports:
      - 3000:80
    deploy:
      restart_policy:
        condition: on-failure
        delay: "5s"
        max_attempts: 5
        window: "30s"

  database:
    container_name: database-server-dab-p1-f8d29c38-5bec-477f-8310-3327a6ca28cd
    image: postgres:14.1
    restart: unless-stopped
    volumes:
      - ./production-database-data:/var/lib/postgresql/data
    env_file:
      - project.env

  flyway:
    image: flyway/flyway:9.11.0-alpine
    depends_on:
      - database
    volumes:
      - ./flyway/sql/:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate
    env_file:
      - project.env

  e2e-playwright:
    entrypoint: "/bin/true"
    build: e2e-playwright
    image: e2e-playwright
    network_mode: host
    depends_on:
      - nginx
    volumes:
      - ./e2e-playwright/tests:/e2e-playwright/tests